### ISSUE TITLE
Add support for repository metadata

### ISSUE THREAD

**Issue by chris-peterson** [eridem/vscode-nupkg#10]
If you add the [newly supported](https://blog.nuget.org/20180827/Introducing-Source-Code-Link-for-NuGet-packages.html) `RepositoryUrl` and `RepositoryType` metadata ([example](https://github.com/chris-peterson/kekiri/blob/master/src/Kekiri/Kekiri.csproj#L19)), you get:

```
   repository: '[object Object]'`
```

should result in:
```
  repository:
    type: git
    url: https://github.com/chris-peterson/kekiri
```

**Comment by eridem** [comment]
It was long ago when you opened this issue @chris-peterson , thanks a lot!
I fixed it today 🎉🙌
