### ISSUE TITLE
Incorrect dependencies interpretetion

### ISSUE THREAD

**Issue by sergey-tihon** [eridem/vscode-nupkg#9]
Package
[SwaggerProvider.0.6.0.nupkg.zip](https://github.com/eridem/vscode-nupkg/files/919737/SwaggerProvider.0.6.0.nupkg.zip)

Package should de displayed as
```
Dependencies:
  FSharp.Core: >=4.0.0
  Newtonsoft.Json: >= 9.0.1
```
instead of 
```
Dependencies:
  FSharp.Core: 4.0.0
  Newtonsoft.Json: 9.0.1
```

<img width="358" alt="2017-04-13_1640" src="https://cloud.githubusercontent.com/assets/1197905/25007100/e16d28fe-2067-11e7-907e-d8841a782fb0.png">

**Comment by eridem** [comment]
Thanks, I will have a look into this

**Comment by eridem** [comment]
I added this functionality now @sergey-tihon. It should appear in the next version: https://marketplace.visualstudio.com/items/eridem.vscode-nupkg/changelog

![screenshot from 2017-04-14 12-30-56](https://cloud.githubusercontent.com/assets/436978/25041202/bc49ee52-210e-11e7-904f-647eb6d0d2bb.png)

Thanks for all your feedback
